limites notas y cortes
Backbone-UTP/Frontend-notas-promedio pull request #20
Opened 2023-09-28 20:39 UTC by seqenenra08

adicioné los limites de porcentajes en los cortes y notas en editar materia

2023-09-28 20:42 UTC, JGaviria0 commented on pagina-notas/app/components/editarNotas.js
> +                        <button type="button" onClick={() => (nameGrade != '' && percentageGrade != '' && obtainedGrade != '') ? (((data1[idMateria].cortes[idCorte === -1 ? data1[idMateria].cortes.le
Cambie a una funcion aparte, para tener el codigo mas limpio.

2023-09-28 20:42 UTC, JGaviria0 requested changes
Algunos cambios

2023-09-28 21:04 UTC, JGaviria0 approved these changes
LGTM

2023-10-01 15:07 UTC, Proman1688 approved these changes

2023-10-01 15:07 UTC, merged